### PR TITLE
Addressed SCP Hanging Issue

### LINKED ISSUE #1345: scp to non existing directory hangs
**"OpenSSH for Windows" version**
7.9.0.0
 
**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
MacOs/Linux/Other

**What is failing**
I am using openssh server for windows version 7.9.0.0 on Windows Server 2016. I am using it for scp and it works if i am uploading files to existing directories. If i will specify target directory not existing on my Windows Server then scp command get stuck and hangs forever. 

Last lines in my client log:
debug1: Sending command: scp -v -t testdir/testfile
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Sending file modes: C0644 0 testfile
...

Last lines in my server log:
8164 2019-02-21 10:18:37.834 debug3: LsaLogonUser Succeeded (Impersonation: 1)
8164 2019-02-21 10:18:37.850 debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe" -z
8164 2019-02-21 10:18:37.865 User child is on pid 2056
8164 2019-02-21 10:18:37.865 debug3: send_rexec_state: entering fd = 5 config len 289
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: send_rexec_state: done
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0
8164 2019-02-21 10:18:37.865 debug3: ssh_msg_send: type 0

Do you know what might cause it?

### PR DESCRIPTION
**Pull request by NoMoreFood**
- Changed fileio_fdopen() to simply return the file descriptor for non-disk file types.
- Addresses issue where an error message in SCP (server side) was not being returned to the pipe which causes the process to hang.  Resolves: https://github.com/PowerShell/Win32-OpenSSH/issues/1345

### CODE REVIEW

File: contrib/win32/win32compat/fileio.c [hunk 1]
```diff
@@ -916,12 +916,19 @@ fileio_fdopen(struct w32_io* pio, const char *mode)
...
 	
 	debug4("fdopen - io:%p", pio);
 
 	if ((wmode = utf8_to_utf16(mode)) == NULL)
 		goto cleanup;
 
+	/* for non-disk files, just return the descriptor */
+	type = GetFileType(pio->handle);
+	if (type != FILE_TYPE_DISK) {
+		return _fdopen(pio->table_index, mode);
```
Comment (manojampalam) [inline contrib/win32/win32compat/fileio.c:929]: relevant info - if the Windows handle associated with "fd" is originally opened as OVERLAPPED (as is the case with all file and pipe handles opened in the posix adapter), all synchronous operations on FILE returned by _fdopen will hang. 

It is for that reason, the subsequent logic works around calling _fdopen directly on file handles. Are you not seeing the above behavior for pipe handles?

Comment (NoMoreFood) [reply contrib/win32/win32compat/fileio.c:929]: No, I do not see a hang -- this returns the handle successfully for the named pipe.  The only "hang" I see is that one caused by the get_final_path_by_handle() returning NULL for a non-disk file which prevents the parent function from receiving the pipe handle which in turns prevents the calling function from receiving the error and closing the connection.

**Review by manojampalam — APPROVED** [review]
