### PR TITLE
make env vars optional for default allow list path

### LINKED ISSUE #2286: v9.8.1.0 x86 MSI install / ssh-agent startup failure
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

x86 MSI install fails because ssh-agent fails to start

current workaround: install via zip package and configure ssh-agent service with custom allow list: `-P "/C:/Program Files/*"`.

fix: update ssh-agent default allowlist that requires both `env:ProgramFiles` and `env:ProgramFilesX86` to exist

### Expected behavior

```console
ssh-agent service should start and install should succeed
```

### Actual behavior

```console
x86 MSI fails to install with error that `ssh-agent service failed to start` - see https://github.com/microsoft/winget-pkgs/pull/180001#issuecomment-2400842841
```

### Error details

_No response_

### Environment data

```PowerShell
N/A
```

### Version

v9.8.1.0

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by tgauth**
# PR Summary
- remove `fatal()` calls if either `env:ProgramFiles` and `env:ProgramFiles(X86)` is not present (and allow list is not configured with `-P`), and instead fallback on initializing an empty allow list
- lowercase provider paths before `match_pattern_list()` to prevent false negatives

## PR Context
- fix https://github.com/PowerShell/Win32-OpenSSH/issues/2286

### CODE REVIEW

File: contrib/win32/win32compat/ssh-agent/agent.c [hunk 1]
```diff
@@ -414,26 +414,41 @@ void
...
-
 	_dupenv_s(&prog_files_x86, &prog_files_x86_len, "ProgramFiles(x86)");
-	if (!prog_files_x86)
-		fatal("couldn't find ProgramFiles environment variable");
-	convertToForwardslash(prog_files_x86);
 
-	size_t allowed_providers_len = 1 + prog_files_len + 4 + prog_files_x86_len + 3;
-	allowed_providers = xmalloc(allowed_providers_len);
-	sprintf_s(allowed_providers, allowed_providers_len, "/%s/*,/%s/*", prog_files, prog_files_x86);
+	if (!prog_files && !prog_files_x86) {
```
Comment (vthiebaut10) [inline contrib/win32/win32compat/ssh-agent/agent.c:426]: What happens in this scenario? Will the initialization succeed?

Comment (tgauth) [reply contrib/win32/win32compat/ssh-agent/agent.c:426]: In this scenario, the allowed providers list is initialized as empty (so no libraries can be loaded) but the ssh-agent service will still start

**Review by vthiebaut10 — APPROVED** [review]
