### PR TITLE
Fix SCP stack overflow when copying over directories

### LINKED ISSUE #1897: SCP -r fails to correctly copy with directory structures deeper than 8 levels
**"OpenSSH for Windows" version**
8.1.0.0
(8.6 also tested)
 
**Server OperatingSystem**
Windows 10 Enterprise

**Client OperatingSystem**
Windows 10 Enterprise

**What is failing**
SCP fails with a recursive copy with a directory structure greater than eight folders deep. Directories up to the 8th directory are created in the destination, but no directories deeper than the 8th directory are created. No files are copied at all.

C:\test\copy_test has a nested file structure:
`copy_test\test_file_0.txt`
`copy_test\level_1\test_file_1.txt`
`copy_test\level_1\level_2\test_file_2.txt`
`...`
`copy_test\level_1\level_2\level_3\level_4\level_5\level_6\level_7\level_8\test_file_8.txt`

Test command:
`scp -r C:\test\copy_test <computername>:C:\test\copy_test2`

This test succeeds with 7.9 and 8.0. It fails with 8.1 and 8.6. If I remove the directory level_8, the tests succeed in all versions.

**Expected output**
C:\test\copy_test2 contains an identical structure and test files.

**Actual output**
C:\test\copy_test2 contains no files and the directory structure stops at level_7.

### PR DESCRIPTION
**Pull request by vthiebaut10**
Fix: https://github.com/PowerShell/Win32-OpenSSH/issues/1897

"SCP -r <source>...<target>" causes a stack overflow when "source" is deeper than a certain number of levels. That is caused because the stack frames for the source and rsource functions, which are called recursively, are too large due to local arrays of size PATH_MAX (defined as 32768 in Win32-OpenSSH). That problem is mitigated by this PR by dynamically allocating memory instead of declaring those arrays with such a large size.

### CODE REVIEW

File: scp.c [hunk 1]
```diff
@@ -1262,8 +1262,9 @@ source(int argc, char **argv)
 	off_t i, statbytes;
 	size_t amt, nr;
 	int fd = -1, haderr, indx;
-	char *last, *name, buf[PATH_MAX + 128], encname[PATH_MAX];
+	char *last, *name, *buf, *encname;
```
Comment (bagajjal) [inline scp.c]: Please add the github issue link to description.

Have #ifdef WINDOWS block as this is a common code. Add some comments why we are deviating from original implementation.

File: scp.c [hunk 2]
```diff
@@ -1274,7 +1280,19 @@ source(int argc, char **argv)
 		if ((fd = open(name, O_RDONLY|O_NONBLOCK, 0)) == -1)
 			goto syserr;
 		if (strchr(name, '\n') != NULL) {
+#ifdef WINDOWS
+			if (!encname) {
+				encname = xmalloc(len + 1);
+				encname_len = len + 1;
+			}
+			while (tmp_len = strnvis(encname, name, encname_len, VIS_NL) >= encname_len) {
+				// check if tmp_len is less than MAX_PATH?
```
Comment (bagajjal) [inline scp.c]: Yes, please have a safe check if (tmp_len < MAX_PATH)

File: scp.c [hunk 3]
```diff
@@ -1309,9 +1327,20 @@ syserr:			run_err("%s: %s", name, strerror(errno));
...
+		      (u_int) (stb.st_mode & FILEMODEMASK),
+			  (long long)stb.st_size, last) >= buf_len) {
+			buf = xreallocarray(buf, tmp_len + 1, sizeof(char));
+			buf_len = tmp_len + 1;
+		}
+#else
 		snprintf(buf, sizeof buf, "C%04o %lld %s\n",
-		    (u_int) (stb.st_mode & FILEMODEMASK),
-		    (long long)stb.st_size, last);
+			(u_int)(stb.st_mode & FILEMODEMASK),
```
Comment (bagajjal) [inline scp.c]: revert the changes here

File: scp.c [hunk 4]
```diff
@@ -1262,8 +1262,14 @@ source(int argc, char **argv)
 	off_t i, statbytes;
 	size_t amt, nr;
 	int fd = -1, haderr, indx;
-	char *last, *name, buf[PATH_MAX + 128], encname[PATH_MAX];
+#ifdef WINDOWS
+	char* last, * name, * buf, * encname;
+	size_t encname_len, buf_len, tmp_len;
+#else
+	char* last, * name, buf[PATH_MAX + 128], encname[PATH_MAX];
```
Comment (bagajjal) [inline scp.c]: Please correct the spacing to improve the readability.

char* last, * name, buf[PATH_MAX + 128], encname[PATH_MAX]; -> char *last, *name, buf[PATH_MAX + 128], encname[PATH_MAX];

Comment (bagajjal) [reply scp.c]: same at line 1266, 1409, 1411

File: scp.c [hunk 5]
```diff
@@ -1309,9 +1327,20 @@ syserr:			run_err("%s: %s", name, strerror(errno));
 				goto next;
 		}
 #define	FILEMODEMASK	(S_ISUID|S_ISGID|S_IRWXU|S_IRWXG|S_IRWXO)
+#ifdef WINDOWS
+		buf_len = strlen(last) * 2;
```
Comment (bagajjal) [inline scp.c]: can you verify this change by having non-english characters in the foldernames and filenames...

File: scp.c [hunk 6]
```diff
@@ -1387,8 +1429,18 @@ rsource(char *name, struct stat *statp)
 			return;
 		}
 	}
-	(void) snprintf(path, sizeof path, "D%04o %d %.1024s\n",
-	    (u_int) (statp->st_mode & FILEMODEMASK), 0, last);
+
+#ifdef WINDOWS
+	while (len = snprintf(path, sizeof path, "D%04o %d %.1024s\n",
+		  (u_int)(statp->st_mode & FILEMODEMASK), 0, last) >= path_len) {
+		path = xreallocarray(path, len + 1, sizeof(char));
```
Comment (bagajjal) [inline scp.c]: We wouldn't come here at all because snprintf writes at max sizeof(path) i.e., path_len?

File: scp.c [hunk 7]
```diff
@@ -1401,14 +1453,29 @@ rsource(char *name, struct stat *statp)
...
+#ifdef WINDOWS
+		if (strlen(name) + 1 + strlen(dp->d_name) >= PATH_MAX - 1) {
+#else 
 		if (strlen(name) + 1 + strlen(dp->d_name) >= sizeof(path) - 1) {
+#endif
 			run_err("%s/%s: name too long", name, dp->d_name);
 			continue;
 		}
+#ifdef WINDOWS
+		while (len = snprintf(path, sizeof path, "%s/%s", name, dp->d_name) >= path_len) {
```
Comment (bagajjal) [inline scp.c]: Line 1457 seems to be doing wrong.. Here we are writing to path but at line we are checking the size as PATH_MAX

File: scp.c (hunk 6 above)
Comment (bagajjal) [reply scp.c]: Have you checked this change by having a file / folder with more than 260 characters?

Comment (vthiebaut10) [reply scp.c]: snprintf returns the number of characters that would have been written if "path" was large enough to fit the whole string in that case. So we can compare path_len to the return value of snprintf to identify if we need to increase the size of "path".

File: scp.c (hunk 7 above)
Comment (vthiebaut10) [reply scp.c]: If I understand correctly, I believe that what this line is trying to check is whether the path is of a valid size, so it throws an error if it's longer than "sizeof(path) - 1", which is equivalent to PATH_MAX - 1 in the original implementation. In our implementation, since we no longer have an array of size PATH_MAX as path, but we allocate up to PATH_MAX chars dynamically as needed, it makes more sense to compare the length of the path to PATH_MAX.

File: scp.c [hunk 8]
```diff
@@ -1471,8 +1472,8 @@ rsource(char *name, struct stat *statp)
 		}
 #ifdef WINDOWS
 		while ((len = snprintf(path, path_len, "%s/%s", name, dp->d_name)) >= path_len) {
-			path = xreallocarray(path, len + 1, sizeof(char));
 			path_len = len + 1;
+			path = xreallocarray(path, path_len, sizeof(char));
```
[the remark this answers is not in the document]
Comment (bagajjal) [reply scp.c:1476]: same at line 1447

[the remark this answers is not in the document]
Comment (vthiebaut10) [reply scp.c:1476]: But I set path_len to len + 1 right before calling realloc.

File: scp.c [hunk 9]
```diff
@@ -1309,9 +1331,25 @@ syserr:			run_err("%s: %s", name, strerror(errno));
 				goto next;
 		}
 #define	FILEMODEMASK	(S_ISUID|S_ISGID|S_IRWXU|S_IRWXG|S_IRWXO)
+#ifdef WINDOWS
+		if (!buf) 
+		{
+			buf_len = ((strlen(last) + 20) < PATH_MAX) ? strlen(last) + 20 : PATH_MAX;
```
Comment (bagajjal) [inline scp.c:1337]: Based on what calculations, you are using 20 here?

Comment (vthiebaut10) [reply scp.c:1337]: To be honest, not very precise calculations. Just by experience, `"C%04o %lld", (u_int) (stb.st_mode & FILEMODEMASK), (long long)stb.st_size` is less than 20 characters on all the tests I ran, I can't know for sure that this is always gonna be the case. I thought about just doing `2 * strlen(last)`, but I think it's more likely to have a filename with a very short name than the rest of the string to be more than 20 characters long.
