### PR TITLE
SFTP transfer broken if buffer > 100Kb

### LINKED ISSUE #1395: SFTP transfer broken if buffer > 100Kb
**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Windows Server 2019 Standard

**Client OperatingSystem**
CentOS Linux release 7.6.1810 (Core)
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

**What is failing**
Using a sftp buffer greater than 102400 fails to transfer large files.
$ ls -l fil
-rw-r--r--. 1 root root 1048576 May 31 16:52 fil
$ sftp -B 102401 sshtest@windows-server
sshtest@windows-server's password:
Connected to windows-server.
sftp> put fil
Uploading fil to /fil
fil                                             9%  100KB   8.8MB/s   00:00 ETA
Couldn't write to remote file "/fil": Failure
sftp>

This is related to the 100Kb read/write buffers in [fileio.c](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/fileio.c#L50)

This can not be triggered from a Windows sftp.exe client because the read buffer is also capped to 102400 bytes.

**Expected output**
File uploaded successfully.

**Actual output**
3716 2019-05-31 16:55:30.395 session opened for local user sshtest from [a.b.c.d]
3716 2019-05-31 16:55:30.395 received client version 3
3716 2019-05-31 16:55:30.395 debug3: request 1: realpath
3716 2019-05-31 16:55:30.395 realpath "."
3716 2019-05-31 16:55:30.395 debug1: request 1: sent names count 1
3716 2019-05-31 16:55:31.656 debug3: request 2: open flags 26
3716 2019-05-31 16:55:31.656 open "/fil" flags WRITE,CREATE,TRUNCATE mode 0644
3716 2019-05-31 16:55:31.656 debug1: request 2: sent handle handle 0
3716 2019-05-31 16:55:31.671 debug1: request 3: write "/fil" (handle 0) off 0 len 102401
3716 2019-05-31 16:55:31.671 debug2: nothing at all written
3716 2019-05-31 16:55:31.671 debug3: request 3: sent status 4
3716 2019-05-31 16:55:31.671 sent status Failure
3716 2019-05-31 16:55:31.671 debug3: request 3: close handle 0
3716 2019-05-31 16:55:31.671 close "/fil" bytes read 0 written 0
3716 2019-05-31 16:55:31.671 debug3: request 3: sent status 0
3716 2019-05-31 16:55:31.671 sent status Success
3716 2019-05-31 16:55:39.810 debug1: read eof
3716 2019-05-31 16:55:39.810 session closed for local user sshtest from [a.b.c.d]

### PR DESCRIPTION
**Pull request by vthiebaut10**
… with buffer>102400 in chunks to avoid failure.
Fix: https://github.com/PowerShell/Win32-OpenSSH/issues/1395

**Description:** fileio.c has a size limit of 102400 bytes for the write buffer, which was causing failures when an Unix client attempted to transfer a file to a Windows server through an sftp connection with a buffer larger than 102400 bytes. The problem was solved by creating a wrapper function that calls the fileio_write function multiple times when the buffer size is greater than the limit.
**Testing:** SFTP file transfers were tested by sending a 1GB file from a Unix client to a Windows server through sftp connections with different buffer sizes. The files were sent correctly both when the buffer size was greater that 102400 and less than 102400 bytes. SCP file transferring was also tested and continue to work correctly after the changes in this PR.

### CODE REVIEW

File: contrib/win32/win32compat/fileio.c [hunk 1]
```diff
@@ -673,6 +673,25 @@ WriteCompletionRoutine(_In_ DWORD dwErrorCode,
 	*((__int64*)&lpOverlapped->Offset) += dwNumberOfBytesTransfered;
 }
 
+
+int 
+fileio_write_wrapper(struct w32_io* pio, const void* buf, size_t max_bytes)
```
Comment (bagajjal) [inline contrib/win32/win32compat/fileio.c]: rename it to bytes_to_copy

File: contrib/win32/win32compat/fileio.c [hunk 2]
```diff
@@ -673,6 +673,25 @@ WriteCompletionRoutine(_In_ DWORD dwErrorCode,
 	*((__int64*)&lpOverlapped->Offset) += dwNumberOfBytesTransfered;
 }
 
+
+int 
+fileio_write_wrapper(struct w32_io* pio, const void* buf, size_t max_bytes) 
+{
+	if (max_bytes <= WRITE_BUFFER_SIZE)
```
Comment (bagajjal) [inline contrib/win32/win32compat/fileio.c:680]: shouldn't this be 
if (max_bytes < WRITE_BUFFER_SIZE)?

Comment (vthiebaut10) [reply contrib/win32/win32compat/fileio.c:680]: fileio_write works if the buffer size is WRITE_BUFFER_SIZE though.

File: sftp-server.c [hunk 3]
```diff
@@ -807,7 +807,11 @@ process_write(u_int32_t id)
 			error("process_write: seek failed");
 		} else {
 /* XXX ATOMICIO ? */
+#ifdef WINDOWS
```
Comment (bagajjal) [inline sftp-server.c]: Please don't make any changes here. This problem is not specific to this scenario. We should fix this in w32_write()

File: contrib/win32/win32compat/w32fd.c [hunk 4]
```diff
@@ -550,6 +550,17 @@ w32_read(int fd, void *dst, size_t max)
 	return fileio_read(fd_table.w32_ios[fd], dst, max);
 }
 
+int
```
Comment (bagajjal) [inline contrib/win32/win32compat/w32fd.c]: remove this.

File: contrib/win32/win32compat/w32fd.c [hunk 5]
```diff
@@ -550,6 +550,17 @@ w32_read(int fd, void *dst, size_t max)
...
+
+	if (fd_table.w32_ios[fd]->type == SOCK_FD)
+		return socketio_send(fd_table.w32_ios[fd], buf, max, 0);
+
+	return fileio_write_wrapper(fd_table.w32_ios[fd], buf, max);
+}
+
 int
 w32_write(int fd, const void *buf, size_t max)
 {
```
Comment (bagajjal) [inline contrib/win32/win32compat/w32fd.c]: Change line 572 below
return fileio_write(fd_table.w32_ios[fd], buf, max); -->> return fileio_write_wrapper(fd_table.w32_ios[fd], buf, max);

File: contrib/win32/win32compat/inc/unistd.h [hunk 6]
```diff
@@ -28,6 +28,8 @@ int w32_write(int fd, const void *buf, size_t max);
 #define writev w32_writev
 int w32_writev(int fd, const struct iovec *iov, int iovcnt);
 
+int w32_write_chunks(int fd, const void* buf, size_t max);
```
Comment (bagajjal) [inline contrib/win32/win32compat/inc/unistd.h]: remove this

File: sftp-server.c (hunk 3 above)
Comment (bagajjal) [reply sftp-server.c]: This is a platform level change rather than an application change.

Comment (vthiebaut10) [reply sftp-server.c]: I did that initially, but that somehow broke cases that worked before, like when the buffer is the default size. I couldn't trace exactly how that was breaking things, but I believe it was because the write function is called by other parts of the code, and that size limit was there to avoid problems on those other calls.
